### ISSUE TITLE
Passing lua functions as parameters

### ISSUE THREAD

**Issue by andybak** [fabSchneider/LiveLua#4]
This might be more of a general Moonsharp question but the Google Group and Discord is pretty dead so I hope you don't mind me making a Github issue out of this. (just go ahead and close it if you prefer)

I'm using your CubeModule sample as a guide but I've got a situation where I want to pass in a function like this: 

`cube.foo(function(p) return p+1 end)`

This is the closest I got:

```
public void foo(Script script)
{
    var f = script.Globals.Values.First(x => x.Function != null).Function;
    script.Call(f);
}
```

I've tried several variations on this. The Unity debugger shows me that I seem to have a reference to the right function but calling it gives a Lua runtime error.

Any suggestions on how to do this correctly?

**Comment by fabSchneider** [comment]
You can use the `Closure` DataType to pass a function as an argument to another function.

Here is a small example:

```csharp
private Closure func;

[LuaHelpInfo("Sets the foo function")]
public void set_foo(Closure func)
{
    this.func = func;
}

[LuaHelpInfo("Calls the foo function")]
public void call_foo(params DynValue[] args)
{
    func.Call(args);
}
```

On the lua side it would then be:


```lua
cube.set_foo(function(x) print(x) end)
cube.call_foo("Hello World")
```

Shame about the Discord being so inactive. I will make sure to post the answer there as well.
